data:
  model: "../../yolo11n.engine"
  device: "cuda"
  preview: True
  outputPath: "./Data"
  outputInterval: 50
camera:
  fps: 30
  stereoRes: 720
  previewRes: "1280x720"
  floodLightIntensity: 1
  laserDotProjectorIntensity: 1
